T5/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "search#index"

  get 'livros/emprestados', to: 'livros#list', as: 'livros_emprestados'
  get 'carteirinhas/emprestimos', to: 'carteirinhas#list', as: 'carteirinhas_emprestimos'
  
  resources :pessoas
  resources :carteirinhas
  resources :autors do
    collection do
      get :autocomplete
    end
  end

  resources :livros do
    collection do
      get :autocomplete
    end
  end

  get "search", to: "search#index"
  get "search/autocomplete", to: "search#autocomplete"
  
  resources :carteirinhas do
    member do
      get "livros"
    end
  end

  
  resources :carteirinhas_livros 
  get   'login', to:  'sessions#login'
  post 'login', to:  'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'logout', to: 'sessions#destroy'
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

T5/app/controllers/search_controller.rb
class SearchController < ApplicationController
  # precisa de admin para pesquisar pessoas
  def index
    @query = params[:query]
    @search_type = params[:search_type]

    @results = {
      autores: [],
      livros: [],
      pessoas: [],
    }

    if @search_type == "pessoas"
      require_admin
    end

    if !@query.blank?
      case @search_type
      when "autores"
        @results[:autores] = Autor.where("nome LIKE ?", "%#{@query}%")
      when "livros"
        @results[:livros] = Livro.where("titulo LIKE ?", "%#{@query}%")
      when "pessoas"
        @results[:pessoas] = Pessoa.where("nome LIKE ?", "%#{@query}%")
      else
        @results[:autores] = Autor.where("nome LIKE ?", "%#{@query}%")
        @results[:livros] = Livro.where("titulo LIKE ?", "%#{@query}%")
        if admin?
          @results[:pessoas] = Pessoa.where("nome LIKE ?", "%#{@query}%")
        end
      end
    else
      # Se a query não estiver presente, retorna todos os registros
      case @search_type
      when "autores"
        @results[:autores] = Autor.all
      when "livros"
        @results[:livros] = Livro.all
      when "pessoas"
        @results[:pessoas] = Pessoa.all
      else
        @results[:autores] = Autor.all
        @results[:livros] = Livro.all
        if admin?
          @results[:pessoas] = Pessoa.all
        end
      end
    end
  end

  def autocomplete
    search_type = params[:search_type]
    query = params[:term]

    results = []
    case search_type
    when "autores"
      results = Autor.where("nome LIKE ?", "%#{query}%").pluck(:nome)
    when "livros"
      results = Livro.where("titulo LIKE ?", "%#{query}%").pluck(:titulo)
    else
      results = Autor.where("nome LIKE ?", "%#{query}%").pluck(:nome) +
                Livro.where("titulo LIKE ?", "%#{query}%").pluck(:titulo) +
                (admin? ? Pessoa.where("nome LIKE ?", "%#{query}%").pluck(:nome) : [])
    end
    render json: results
  end
end

T5/app/views/search/index.html.erb
<%= form_tag(search_path, method: :get) do %>
<div class="input-group mt-5">
  <div class="form-group">
    <%= text_field_tag :query, @query, id: 'query', class: 'form-control', placeholder: "Digite sua pesquisa..." %>
  </div>
  <%= submit_tag "Pesquisar", class: 'btn btn-primary' %>
  <div class="form-group">
    <% search_options = [['Autores', 'autores'], ['Livros', 'livros']] %>
    <% search_options << ['Pessoas', 'pessoas'] if admin? %>
    <%= select_tag :search_type, options_for_select(search_options, params[:search_type]), id: 'search_type', class: 'form-control', include_blank: "Pesquisar por..." %>
  </div>
</div>
<% end %>

<% if @query.present? %>
  <h2>Resultados da Pesquisa para "<%= @query %>"</h2>
<% else %>
  <h2>Todos os Registros</h2>
<% end %>

<table class="table table-striped">
  <% if @results[:autores].any? %>
    <h2 class="d-flex justify-content-center">Autores</h2>
    <table class="table table-striped table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Nacionalidade</th>
          <th scope="col">Livros</th>
        </tr>
      </thead>
      <tbody>
      <% @results[:autores].each do |autor| %> 
          <tr>
            <td><%= link_to autor.nome, autor_path(autor) %></td>
            <td><%= autor.nacionalidade %></td>
            <td><%= link_to autor.livros.count, livros_emprestados_path(autor_id: autor.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <% if @results[:livros].any? %>
    <h2 class="d-flex justify-content-center">Livros</h2>
    <table class="table table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Título</th>
        <th scope="col">Autor</th>
        <th scope="col">Ano</th>
        <th scope="col">Gênero</th>
        <th scope="col">Quantidade</th>
        <th scope="col">Emprestados</th>
      </tr>
    </thead>
    <tbody>
      <% @results[:livros].each_with_index do |livro| %>
        <tr>
          <td><%= link_to livro.titulo, livro_path(livro) %></td>
          <td><%= livro.autor.nome %></td>
          <td><%= livro.ano %></td>
          <td><%= livro.genero %></td>
          <td><%= livro.quantidade %></td>
          <td><%= link_to livro.emprestados, carteirinhas_emprestimos_path(livro_id: livro.id) %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
  <% if @results[:pessoas].any? %>
    <h2 class="d-flex justify-content-center">Pessoas</h2>
    <table class="table table-striped table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Email</th>
          <th scope="col">Role</th>
        </tr>
      </thead>
      <tbody>
        <% @results[:pessoas].each do |pessoa| %>
          <tr>
            <td><%= link_to pessoa.nome, pessoa_path(pessoa) %></td>
            <td><%= pessoa.email %></td>
            <td><%= pessoa.privilegio %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</table>