T5/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "search#index"

  get 'livros/emprestados', to: 'livros#list', as: 'livros_emprestados'
  get 'carteirinhas/emprestimos', to: 'carteirinhas#list', as: 'carteirinhas_emprestimos'
  
  resources :pessoas
  resources :carteirinhas
  resources :autors do
    collection do
      get :autocomplete
    end
  end

  resources :livros do
    collection do
      get :autocomplete
    end
  end

  get "search", to: "search#index"
  get "search/autocomplete", to: "search#autocomplete"
  
  resources :carteirinhas do
    member do
      get "livros"
    end
  end

  
  resources :carteirinhas_livros 
  get   'login', to:  'sessions#login'
  post 'login', to:  'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'logout', to: 'sessions#destroy'
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

T5/app/models/carteirinha.rb
class Carteirinha < ApplicationRecord
  belongs_to :pessoa
  has_and_belongs_to_many :livros, dependent: :destroy
  validates :podeEmprestar, inclusion: { in: [true, false] }
end

T5/app/controllers/carteirinhas_controller.rb
class CarteirinhasController < ApplicationController
  before_action :require_admin, only: [:index, :destroy]

  def index
    @carteirinhas = Carteirinha.all
  end


  def show
    # apenas mostra a carteirinha se for o admin ou a pessoa logada
    if current_pessoa.admin? || current_pessoa == Carteirinha.find(params[:id]).pessoa
      @carteirinha = Carteirinha.find(params[:id])
      @carteirinhas_livros = CarteirinhasLivro.where(carteirinha_id: @carteirinha.id)
    else
      require_admin
    end
  end


  def destroy
    @carteirinha = Carteirinha.find(params[:id])
    @carteirinha.destroy

    redirect_to carteirinhas_path, status: :see_other
  end

  def livros
    @carteirinha = Carteirinha.find(params[:id])
    @carteirinhas_livros = Emprestimo.where(carteirinha_id: @carteirinha.id).includes(:livro)
  end
  
  def list
    if params[:livro_id].present?
      @livro = Livro.find(params[:livro_id])
      @carteirinhas = Carteirinha.all
      @carteirinhas_livro = CarteirinhasLivro.new(livro: @livro)
    end
    render :list
  end

  private
  def carteirinha_params
    params.require(:carteirinha).permit(:podeEmprestar)
  end
end

T5/app/helpers/carteirinha_helper.rb
module CarteirinhaHelper
end

T5/app/views/carteirinhas/index.html.erb
<h1>Empréstimos</h1>

<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Dono</th>
      <th scope="col">ID</th>
      <th scope="col">Livros emprestados</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% if @carteirinhas.present? %>
      <% @carteirinhas.each do |carteirinha| %>
        <tr>
          <td><%= carteirinha.pessoa.nome %></td>
          <td><%= carteirinha.id %></td>
          <td><%= carteirinha.livros.count %></td>
          <td>
            <%= link_to 'Livros emprestados', livros_emprestados_path(carteirinha_id: carteirinha) %> | 
            <%= link_to 'Excluir', carteirinha_path(carteirinha), method: :delete, data: { confirm: 'Tem certeza?' } %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>


<%= link_to 'Novo Empréstimo', new_carteirinha_path %>

T5/app/views/carteirinhas/list.html.erb
<%
=begin%>
    isso é para listar as carteirinhas que emprestaram um certo livro recebidos pelo controller, em uma lista de livros, com um link para a página de detalhes de cada livro, a lista é horizontal, até atingir o limite da tela, depois passa para a linha de baixo

<%
=end%>
<h1>Carteirinhas</h1>

<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
        <th scope="col">Nome</th>
        <th scope="col">ID</th>
    </tr>
    </thead>
    <tbody>
    <% @carteirinhas.each do |carteirinha| %>
        <tr>
            <td><%= link_to carteirinha.pessoa.nome, carteirinha_path(carteirinha.pessoa) %></td>
            <td><%= carteirinha.id %></td>
        </tr>
    <% end %>
    </tbody>
</table>

T5/app/views/carteirinhas/livros.erb
<h1>Livros emprestados</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Gênero</th>
      <th>Ano</th>
      <th>Autor</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% if @carteirinhas_livros.present? %>
      <% @carteirinhas_livros.each do |carteirinha_livro| %>
        <tr>
          <td><%= carteirinha_livro.livro.titulo %></td>
          <td><%= carteirinha_livro.livro.genero %></td>
          <td><%= carteirinha_livro.livro.ano %></td>
          <td><%= carteirinha_livro.livro.autor.nome %></td>
          <td>
            <%= link_to 'Detalhes', livro_path(carteirinha_livro.livro) %> |
            <%= link_to 'Editar', edit_livro_path(carteirinha_livro.livro) %> |
            <%= link_to 'Excluir empréstimo', carteirinha_livro_path(carteirinha_livro), data: { turbo_method: :delete, turbo_confirm: "Tem certeza?"} %></li>
          </td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
</table>

T5/app/views/carteirinhas/show.html.erb
<h1>Detalhes da Carteirinha</h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card mb-3">
        <div class="card-header">
          <h4>Informações da Carteirinha</h4>
        </div>
        <div class="card-body">
          <p>
            <strong>ID da carteirinha:</strong>
            <%= @carteirinha.id %>
          </p>
          
          <p>
            <strong>Nome:</strong>
            <%= @carteirinha.pessoa.nome %>
          </p>
          
          <p>
            <strong>Livros emprestados:</strong>
            <%= link_to @carteirinha.livros.count, livros_emprestados_path(carteirinha_id: @carteirinha.id), class: 'btn btn-info' %>
          </p>
          
          <div class="d-flex justify-content-between">
            <%= link_to 'Editar', edit_pessoa_path(@carteirinha.pessoa), class: 'btn btn-warning' %>
            <%= link_to 'Deletar carteirinha', carteirinha_path(@carteirinha), data: { turbo_method: :delete, turbo_confirm: "Tem certeza?" }, class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

T5/app/views/carteirinhas/update.html.erb
<h1>Carteirinha#update</h1>
<p>Find me in app/views/carteirinha/update.html.erb</p>