T5/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "search#index"

  get 'livros/emprestados', to: 'livros#list', as: 'livros_emprestados'
  get 'carteirinhas/emprestimos', to: 'carteirinhas#list', as: 'carteirinhas_emprestimos'
  
  resources :pessoas
  resources :carteirinhas
  resources :autors do
    collection do
      get :autocomplete
    end
  end

  resources :livros do
    collection do
      get :autocomplete
    end
  end

  get "search", to: "search#index"
  get "search/autocomplete", to: "search#autocomplete"
  
  resources :carteirinhas do
    member do
      get "livros"
    end
  end

  
  resources :carteirinhas_livros 
  get   'login', to:  'sessions#login'
  post 'login', to:  'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'logout', to: 'sessions#destroy'
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

T5/app/models/autor.rb
class Autor < ApplicationRecord
  validates :nome, presence: true
  validates :nacionalidade, presence: true, length: { minimum: 2 }
  has_many :livros, dependent: :destroy

  scope :search, ->(query) {
    where('nome LIKE ?', "%#{query}%")
  }
end

T5/app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @autors = Autor.all
  end

  def show
    @autor = Autor.find(params[:id])
    @livros = @autor.livros
  end

  def new
    @autor = Autor.new
  end

  def create
    @autor = Autor.new(autor_params)
    
    if @autor.save
      redirect_to @autor
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @autor = Autor.find(params[:id])
  end

  def update
    @autor = Autor.find(params[:id])

    if @autor.update(autor_params)
      redirect_to @autor
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @autor = Autor.find(params[:id])
    @autor.destroy

    redirect_to autors_path, status: :see_other
  end

  def autocomplete
    @autores = Autor.where('nome LIKE ?', "%#{params[:term]}%")
    render json: @autores.pluck(:nome)
  end

  private

  def autor_params
    params.require(:autor).permit(:nome, :nacionalidade)
  end
end

T5/app/views/autors/_form.html.erb
<%= form_with model: autor do |form| %>
  <div>
    <%= form.label :nome %><br>
    <%= form.text_field :nome %>
    <% autor.errors.full_messages_for(:nome).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :nacionalidade %><br>
    <%= form.text_area :nacionalidade %><br>
    <% autor.errors.full_messages_for(:nacionalidade).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

T5/app/views/autors/edit.html.erb
<h1>Editar Autor</h1>

<%= render "form", autor: @autor %>

T5/app/views/autors/index.html.erb
<h1>Autores</h1>

<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Nacionalidade</th>
      <th scope="col">Livros</th>
      <th scope="col">Editar</th>
      <th scope="col">Excluir</th>
    </tr>
  </thead>
  <tbody>
    <% @autors.each do |autor| %>
      <tr>
        <td><%= autor.nome %></td>
        <td><%= autor.nacionalidade %></td>
        <td><%= link_to autor.livros.count, livros_emprestados_path(autor_id: autor.id) %></td>
        <td><%= link_to "Editar", edit_autor_path(autor) %></td>
        <td><%= link_to "Excluir", autor_path(autor), data: { turbo_method: :delete, turbo_confirm: "Tem certeza?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Inserir novo autor", new_autor_path %>

T5/app/views/autors/new.html.erb
<h1> Novo Autor </h1>


<%= render "form", autor: @autor %>

T5/app/views/autors/show.html.erb
<h1><%= @autor.nome %></h1>

<p>Nacionalidade: <%= @autor.nacionalidade %></p>

<h1>Livros:</h1>


<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Título</th>
      <th scope="col">Autor</th>
      <th scope="col">Ano</th>
      <th scope="col">Gênero</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Emprestados</th>
    </tr>
  </thead>
  <tbody>
    <% @autor.livros.each do |livro| %>
      <tr>
        <td><%= livro.titulo %></td>
        <td><%= livro.autor.nome %></td>
        <td><%= livro.ano %></td>
        <td><%= livro.genero %></td>
        <td><%= livro.quantidade %></td>
        <td><%= livro.emprestados %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h2>Opções</h2>
<ul>
  <li><%= link_to "Editar", edit_autor_path(@autor) %></li>

<li><%= link_to "Excluir", autor_path(@autor), data: {
  turbo_method: :delete,
                    turbo_confirm: "Tem certeza?"
                  } %></li>
</ul>