T5/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "search#index"

  get 'livros/emprestados', to: 'livros#list', as: 'livros_emprestados'
  get 'carteirinhas/emprestimos', to: 'carteirinhas#list', as: 'carteirinhas_emprestimos'
  
  resources :pessoas
  resources :carteirinhas
  resources :autors do
    collection do
      get :autocomplete
    end
  end

  resources :livros do
    collection do
      get :autocomplete
    end
  end

  get "search", to: "search#index"
  get "search/autocomplete", to: "search#autocomplete"
  
  resources :carteirinhas do
    member do
      get "livros"
    end
  end

  
  resources :carteirinhas_livros 
  get   'login', to:  'sessions#login'
  post 'login', to:  'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'logout', to: 'sessions#destroy'
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

T5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-secundario">
      <div class="container">
        <a class="navbar-brand" href="#">
        <h1>Sistema da biblioteca</h1></a>
        <!-- Botão para colapsar o menu -->
        <span class="navbar-text ml-auto">
          <% if current_pessoa %>
            Logado como: <%= current_pessoa.nome %>
          <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-danger btn-sm ml-2" %>
          <% else %>
            <%= render 'sessions/form' %>
          <% end %>
        </span>
        <% if logged_in? %>
        <button class="btn bg-light" type="button" data-bs-toggle="collapse"  data-bs-target="#adminMenu" aria-controls="adminMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <% end %>
      </div>
    </nav>
    <!-- Menu de navegação -->
        <div class="collapse bg-light " id="adminMenu">
          <ul class="navbar-nav mr-auto me-5 d-flex align-items-end">
            <% if admin? %>
              <li class="nav-item ">
                <%= link_to 'Novo Empréstimo', new_carteirinhas_livro_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Novo Usuário', new_pessoa_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Novo Livro', new_livro_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Novo Autor', new_autor_path, class: 'nav-link' %>
              </li>
            <% end %>
            <li class="nav-item">
            <%
=begin%>
  se estiver logado, exibe o link para a página de perfil
<%
=end%>
          <% if logged_in? %>
            <%= link_to 'Perfil', pessoa_path(current_pessoa), class: 'nav-link' %>
          <% end %>
            </li>
          </ul>
        </div>
        
    <%= yield %>
  </body>
</html>